name: greeting
on: push
jobs: 
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: greet
        run: |
          echo "hello "
          echo "hello 2"
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: run python
        run: python check.py
